spring:
  datasource:
    url: jdbc:mysql://local-mysql:3306/wallet?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
    username: in2admin #root
    password: in2pass #1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
    properties:
      jakarta.persistence.sharedCache.mode: UNSPECIFIED
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  security:
    user:
      name: in2test
      password: in2pass

server:
  port: 8083

in2:
  openapi:
    local-url: http://localhost:8083
    dev-url: https://walletapidev.in2.es

app:
  url:
    api: http://localhost:8083
    orion_context_broker: http://wallet-orion:1026/v2/entities